language: cpp
compiler: gcc
os: linux
dist: bionic

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache

addons:
    apt:
        packages:
            - xorg-dev
            - lcov

install:
- mkdir -p $HOME/.cache/cmake &&
  wget -qO- https://github.com/Kitware/CMake/releases/download/v3.17.0/cmake-3.17.0-Linux-x86_64.tar.gz | tar -xzC $HOME/.cache/cmake --strip-components 1 &&
  export PATH=$HOME/.cache/cmake/bin:$PATH

script: bash build.sh
