language: cpp
compiler: gcc
os: linux
dist: bionic

# see https://docs.travis-ci.com/user/caching/
cache:
- directories:
  - $HOME/.cache

# see https://docs.travis-ci.com/user/gui-and-headless-browsers
services: 
  - xvfb

addons:
    apt:
        packages:
            - xorg-dev
            - lcov

script: bash build.sh
