[[block]]
id = 1
name = 'stone'
opaque = true
textures = [ 'stone', ]
str = [ 
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
]

[[block]]
id = 2
name = 'grass'
opaque = true
textures = [ 'grass_side', 'grass_top', 'dirt', ]
str = [
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
    0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
    1, 1, 2, 1, 0, 2, 0, 1, 2, 0, 0, 2,
    0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
]

[[block]]
id = 3
name = 'dirt'
opaque = true
textures = [ 'dirt', ]
str = [
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
]

[[block]]
id = 4
name = 'cobblestone'
opaque = true
textures = [
    'cobblestone',
]
str = [
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
]

[[block]]
id = 5
name = 'planks'
opaque = true
textures = [ 'planks', ]
str = [
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
    0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
]

[[block]]
id = 17
name = 'wood'
opaque = true
textures = [ 'wood_side', 'wood_top', ]
str = [
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
    0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
    1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
    0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
]

[[block]]
id = 18
name = 'leaves'
opaque = false
textures = [ 'leaves', ]
str = [
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
]

[[block]]
id = 40
name = 'crafting_table'
opaque = true
textures = [ 'crafting_table_side', 'crafting_table_top', 'crafting_table_front', ]
str = [
    0, 1, 2, 0, 0, 2, 1, 1, 2, 1, 0, 2,
    1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
    0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
    1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
    0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
]

